### ISSUE TITLE
maximizing a c.window() causes infinite flickering

### ISSUE THREAD

**Issue by chwba** [potocpav/python-concur#33] opened 2020-10-31 02:35 UTC

**Comment by chwba** [comment] 2020-11-01 12:25
bump

**Comment by potocpav** [comment] 2020-11-02 15:33
Maximizing the application? Works fine for me on Ubuntu. Is it a Windows issue?

**Comment by chwba** [comment] 2020-11-02 19:52
Take a look at this screencast:
https://nextcloud.mnwd.in/s/dcYZf38Gsf9PXcy
I pushed the example to: https://github.com/chwba/concur_gui_test/blob/847d94a4d85271131023d2435a9c23d1698e6e39/src/features/nice_feature/nice_feature_gui.py#L59

**Comment by potocpav** [comment] 2020-11-03 08:41
Thanks for the information. Your code also flickers on my machine. I already had a similiar issue in the past, but I can't remember what was the cause. Will investigate.

**Comment by potocpav** [comment] 2020-11-03 08:51
perhaps related to https://github.com/ocornut/imgui/issues/2286

**Comment by potocpav** [comment] 2020-11-03 09:02
Caused by nested windows (https://github.com/ocornut/imgui/issues/2109#issuecomment-426960879). You shouldn't really nest windows, since the code inside a window is only executed when the window is open. This leads to a feedback loop:

1. Window is rendered, which causes a nested window to be rendered
2. The nested window displays in a tab, which hides the parent window
3. Parent window doesn't render because it's hidden. This causes the child window to disappear.
4. The parent window is now visible again, and it is rendered.

That's the reason the [docs for `window`](https://potocpav.github.io/python-concur-docs/master/widgets.html#concur.widgets.window) say they can't be nested. I will add this issue to the docs & faq.

**Comment by chwba** [comment] 2020-11-03 12:53
Alright, great, ill push the final ammendmends as discussed in the PR in a bit.

**Comment by potocpav** [comment] 2020-11-04 08:33
Updated docs. Closing.

**Closed by potocpav** 2020-11-04 08:33 UTC

**Comment by chwba** [comment] 2020-11-04 13:09
Can you implement & push a workaround for this problem according to what how it is currently implemented in this repo?

**Comment by potocpav** [comment] 2020-11-06 16:11
here you go https://github.com/chwba/concur_gui_test/pull/6
